name: stage
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - holoviews
  - hvplot
  - geopandas
  - rioxarray
  - spyndex
  - gdal==3.10.1
  - natsort
  - xarray
  - rioxarray
  - sklearn